spring:

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/boreas?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: wang230219
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  servlet:
    multipart: 10MB
upload-path: E:/fileUpload/
download-path: E:/download/
person:
  name: 张三
  age: 20
  maps: {a: 1, b: 2}


